from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 282)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 391, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 75 11pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("font: 75 11pt \"Arial\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 75 11pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_soll = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_soll.setText("")
        self.label_soll.setObjectName("label_soll")
        self.gridLayout.addWidget(self.label_soll, 0, 1, 1, 1)
        self.label_ist = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_ist.setText("")
        self.label_ist.setObjectName("label_ist")
        self.gridLayout.addWidget(self.label_ist, 1, 1, 1, 1)
        self.label_n = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_n.setText("")
        self.label_n.setObjectName("label_n")
        self.gridLayout.addWidget(self.label_n, 2, 1, 1, 1)
        self.label_ist.setStyleSheet("font: 75 11pt \"Arial\";")
        self.label_n.setStyleSheet("font: 75 11pt \"Arial\";")
        self.label_soll.setStyleSheet("font: 75 11pt \"Arial\";")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Auswertung zyklisch"))
        self.label_2.setText(_translate("Dialog", "Istwert ε in Prozent:"))
        self.label.setText(_translate("Dialog", "Sollwert ε in Prozent:"))
        self.label_3.setText(_translate("Dialog", "Erforderliche Anzahl der Einzelzeit n:              "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
